version: '2'

services:
  ririko-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ririkoai/ririkobot-dashboard-development
    container_name: ririko-bot-frontend
    ports:
      - "8100:8100"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./config:/app/config
    environment:
      - NODE_ENV=development

  ririko-bot-backend:
    image: ririkoai/ririkobot-development
    container_name: ririko-bot-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
    ports:
     - "3000:3000"